
defaults:
  - qd: cvtmapelites
  - env: qd_bio_dna
  - mutation_model: mutator_helix
  - fitness_model: fitness_TFBind10_ensemble
  - _self_

wandb_group: run_elm
run_name: ""
wandb_mode: online
output_dir: logs/
