env_name: qd_bio_env
timeout: 5.0
sandbox: false
sandbox_server: http://localhost:5000
processes: 1
batch_size: 128
debug: false
seed: 42
behavior_space:
  - [0, 1]
  - [0, 1]
  - [0, 1]
sequence_length: 50
alphabet: [0, 1, 2, 3]
size_of_refs_collection: 16384
bd_type: freq
normalize_bd: true
distance_normalization_constant: -1
task: UTR-ResNet-v0-CUSTOM
retrain_fitness_model: false
